### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by WakanaYuki** [shaked6540/csharp#1]
Heya,

this project looks really awesome and exciting! This is a great tool.
Some things I discovered while testing it out where that it's already really advanced. One thing that got kind of a habit thing is hitting control + c to cancel an input, which closed the program, which is a probably unfixable limitation, maybe there's a way to implement a hotkey like that to cancel the current input? Just an idea.
Another thing that came to my mind is when testing with importing a library maybe having a way to refresh all user imported libraries with a command? So that if I import a library, test something, edit the library again and build, that I just need to input "refresh()" or something and it refreshes all user imported dlls/libraries.
Another thing where I'm not sure if that's already build in is something like the "#define" function is C++ when importing a library for example it can get tedious to write out the name all the time, or with some functions, so #define would be used like this:
#define CW Console.WriteLine
#define sc SomeLibrary.SomeClass
So now the user just needs to write:
CW("Hello World!")
or
sc.SomeMethod()

These are just some ideas which would probably be cool to see in this project ^^

Another thing is that I wanted to look into adding such a solution myself, but this project hasn't got a license yet? I have not much experience with legal and license stuff, but I don't know if forking or contributing this project etc is allowed like that without a license? Please correct me if I'm wrong. I am currently trying to implement a auto complete feature for example.

This projects looks awesome and I'll defenetly keep an out for further updates. Thank you for creating this awesome tool.

**Comment by shaked6540** [comment]
It is possible to 'override' the behavior of ctrl+c, but what do you expect to happen once that is pressed? An input must be provided for the program to run, otherwise there is nothing to execute. Do you want it to clean the current line, and start from 0? 

The 'refresh assemblies' suggestion is interesting, but it might be impossible. Consider the following scenario: I have an assembly that defines class A like so: 
```cs
class A
{
    private string a;
    public string b;

   public A(string a, string b) {}
}
```
I create a new A object, like this: `var a = new A("hello", "world");`

And then, I load an updated version of that assembly that defines the same type A as: 
```cs
class A
{
    private int a;
    private int b;

    public A(int a, int b) {}
}
```

It would break the type in memory, or maybe cause some unintended behavior. I actually don't know what will happen in that case. I need to run some tests with that but I don't think it will be as simple as removing that assembly and adding a new one

The #define directive is kind of already implemented, but not the exact same way as it is in c\c++. You could define whatever you want in the BeforeScript file which you can specify in the Config.json. I showed how to do it in the example BeforeScript.cs file, specifically this line: `public static void cw(object o) => Console.WriteLine(o);`
As for the `#define sc SomeLibrary.SomeClass` scenario, you could probably do `using sc = SomeLibrary.SomeClass`. 
I will think about that more later, because I'm not sure how to implement something like that. The easiest way would be to replace all occurrences of `sc` using regex with what you defined it to be, but it can cause a lot of problems if a method name or a type name contains `sc` in it.

And as for adding things yourself, feel free to make pull requests, I don't have a license because I don't know anything about legal stuff too. I think I will add a license file to clarify that, it would probably be an MIT license. 

Thanks for the feedback!

**Comment by WakanaYuki** [comment]
About the first thing with the CTRL + C, I more mean a break hotkey, so that you can cancel the currently written statement and clear the input. (it's just something I think many users (me included) are used to with command line applications, it's like a reflex. But I understand the technical limitations. I felt pretty stupid reading you answer, I should've known at least half of it ^^').

I think as for the refresh assembly, that is probably very changellanging to impossible yeah :/ but it would be a pretty interesting and useful feature, maybe theres a way to clear the memory of that part of the assembly? I mean one thing that can be expected, is that every created object that comes from the libraries/DLL classes that are refreshed will be gone.

For the #define feature, yeah, I saw that and it is possible to do with adding static methods into the startup up. I think it would be a cool and interesting feature, but I agree it's probably too difficult to implement :/ or rather it will probably bring many bugs and issue into the program.

Like mentioned I am currently trying to implement a auto suggestion features, which records previous user inputs and saves them into a .txt file. The suggestion would only save the everyhting before '(' (for now), so that in the future the program will suggest "Console.WriteLine" for example. Maybe in the distant future I'll be able to implement a whole suggest with cw + tab + tab for example which will create a "Console.WriteLine("");" with the cursor between the two ". But I think to implement all that, I would either need to go away from the Console.ReadLine(), or extend it myself, or find a open source library that can do that.

Anyway, thank you for this amazing project again and I hope the changes I am trying to implement aren't something you dislike. We can discuss about that more if you want, I don't mind trying to implement them differently or something completely different in that direction.

**Comment by shaked6540** [comment]
Regarding the auto complete feature, I'm actually working on such an auto complete feature right now lol. It works pretty ok for now but there are some bugs, It completes whenever you press tab and cycles the possible completions. It looks like this right now: 
![gif](https://i.imgur.com/Wn8sYwU.gif)

I plan to finish it in about 2 days, maybe you could expand on that if you're interested in it

**Comment by shaked6540** [comment]
I was optimistic about the autocomplete feature, it's going to take a couple more days.

**Comment by WakanaYuki** [comment]
Hey, just looked into the autocomplete feature and it looks really awesome.
I will look into the code later today and try some stuff out with it. Could you license it soon? I have some fun ideas I want to try and implement ^^

**Comment by shaked6540** [comment]
I've added a license

**Comment by WakanaYuki** [comment]
Thank you.
I am noticing I maybe should've split this up into multiple issues. You can if you want close the issue, it was mainly feedback, that doen't have to be implemented. I am happy, that you have read through this and gave some response and thought into it.
Thank you for this awesome project and reading through and responding to my feedback.

**Comment by shaked6540** [comment]
No problem :)
